#!/bin/bash
# 创建每日IT简报的 OpenClaw Cron 任务

echo "=== 每日IT简报 Cron 任务配置 ==="
echo ""
echo "任务名称: daily-it-briefing"
echo "执行时间: 每天 08:00 (Asia/Shanghai)"
echo "执行内容: 生成6章节IT简报并发送到微信"
echo ""
echo "配置文件位置: ~/.openclaw/cron-daily-it-briefing.json"
echo ""
echo "当前状态: 等待通过 Gateway API 创建任务"
echo ""
echo "由于需要提升权限（scope upgrade），请手动执行以下命令："
echo ""
echo "  openclaw cron create \\"
echo "    --name 'daily-it-briefing' \\"
echo "    --cron '0 8 * * *' \\"
echo "    --tz 'Asia/Shanghai' \\"
echo "    --message '生成每日IT简报：包含6个章节 - IT行业最新动态、AI及机器人行业最新动态、Agent热门Skill、GitHub热门项目、个人OPC优秀案例、教育+AI行业新产品。搜索今日相关资讯，格式化为Markdown后发送到微信和飞书。' \\"
echo "    --to 'o9cq800mKf-NUE3yarSzDNB-1-S0@im.wechat'"
echo ""
echo "或者，你也可以："
echo "1. 打开 OpenClaw 配置界面"
echo "2. 导航到 Cron 任务管理"
echo "3. 手动添加任务（使用上述 JSON 配置）"
